---
abstract: 'implementation of WebID (a.k.a. FOAF+SSL)'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Web::ID
name: Web-ID
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Crypt::X509: 0
  DateTime: 0
  Digest::SHA: 0
  List::MoreUtils: 0
  Moose: 0
  MooseX::Types: 0
  Path::Class: 0
  Plack: 0
  RDF::Query: 2.900
  RDF::Trine: 1.000
  Sub::Exporter: 0
  URI: 0
  namespace::sweep: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Web-ID
  homepage: https://metacpan.org/release/Web-ID
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-web-id
version: 1.922
